### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by fbracht** [chrisma/Hearthstone-Hotkeys#4]
Is is even possible? Do you plan on doing it?

**Comment by chrisma** [comment]
Hello!

[Autohotkey](http://ahkscript.org/) in which the script is written in at the moment only supports windows.
Unfortunately I don't own a Mac and so can't test any scripts for it, so there is currently no plan to support Mac OS.

There is [IronAHK](https://github.com/polyethene/IronAHK) an (outdated) cross-platform rewrite that could work, you'd have to try it out.

Alternatively you could try rewriting this script using one of the [Autohotkey alternatives for Mac](http://alternativeto.net/software/autohotkey/?platform=mac).

**Comment by chrisma** [comment]
There are currently no plans to support Mac.
